### PR TITLE
improve pre-commit

### PR DESCRIPTION
**Pull request by juanitorduz**
Closes https://github.com/s3alfisc/pyfixest/issues/369

It also suggests the following changes:

1. Replace black with the ruff formatted (https://docs.astral.sh/ruff/formatter/), which is much faster, and you are already using ruff anyway ;) 

2. Add other useful pre-commit hooks.

Many files have changed a bit because I ran `pre-commit run --all-files` from the terminal. Let me know if some of the changes are unwanted, and I will try to revert them.

### CODE REVIEW

**Comment by juanitorduz** [comment]
(I think you need to approve the workflow to see if the changes pass 🤞 )

**Comment by juanitorduz** [comment]
The pre-commit is 🟢 ! https://github.com/s3alfisc/pyfixest/actions/runs/8821154706/job/24216957377?pr=373 Yay!

**Review by s3alfisc — APPROVED** [review]
This looks excellent, thank you @juanitorduz!

**Comment by s3alfisc** [comment]
@all-contributors please add @ juanitorduz for infrastructure

**Comment by s3alfisc** [comment]
https://github.com/all-contributors please add @juanitorduz for infrastructure

**Pull request merged**
