### PR TITLE
Migrate docs build to github workflow

### PR DESCRIPTION
**Pull request by NKeleher**
This PR migrates the quarto docs from a local build to a build run on Github Actions. Covers https://github.com/s3alfisc/pyfixest/issues/295

Apologies for this being a large PR, but I think it will help with several workflows:
- added sections to the ci-tests.yaml to build documentation with quarto after tests pass
- general updates to the ci-tests.yaml (upgrade imported actions, and use poetry rather than pip to build environment for pytests)
- added `.pre-commit-config.yaml`  to check yaml, toml, and github workflows
- updated poetry.lock with the pre-commit addition (this has an added benefit of updating numpy such that pyfixest will run on Python 3.12
- Streamlined the pytest.ini so that it's included in the pyproject.toml
- removed the local quarto docs build artifacts to reduce the codebase covered in source control. Now that all of the docs are build through github actions an the `gh-pages` branch, the versions on the main/master branch are no longer necessary. This will reduce the amount of code that needs to be reviewed so that developers can just focus on the core Quarto assets (.qmd, .ipynb, .py, .etc)  

I have confirmed that all tests pass on Python 3.8, 3.9, 3,10, 3.11, and 3.12. The Quarto website builds with the "Build Docs" task. I did not run the "Publish Docs" task because that can only run when this PR is merged to the main/master branch.

image

To make sure that the "Publish Docs" task successfully updates the website, make sure that the [Github Pages settings](https://github.com/s3alfisc/pyfixest/settings/pages) point to the `gh-pages` branch and `/root` directory:
image

### CODE REVIEW

**Comment by NKeleher** [comment]
@s3alfisc  - tests passed and docs build can be migrated to gh-actions with this PR.

**Comment by s3alfisc** [comment]
Will review this once I'm back home from work! Thank you!

**Review by s3alfisc — APPROVED** [review]

**Comment by s3alfisc** [comment]
This is a fantastic PR @NKeleher. I am particularly excited to run all tests in parallel - testing time is now down to approximately 5 minutes, which is amazing 🎉.

I changed the github pages deployment to `root`, and the website now builds automatically! Though at the moment, it only displays the readme: [link ](https://s3alfisc.github.io/pyfixest/). Building the site ran into an error - I will investigate this; it might be related to another PR I just merged. 

Anyways, thanks so much!

**Comment by NKeleher** [comment]
Glad the tests are running faster!

I can take a closer look at the quartodocs failure below later tonight, if you don't find anything in a conflicting merge. 

https://github.com/s3alfisc/pyfixest/actions/runs/7805473906/job/21290296854

**Comment by s3alfisc** [comment]
I think I figured it out - I added some new examples to `etable()` and this line is what causes this error message `

> 2024-02-06 20:24:47,771 - quartodoc.autosummary - INFO - Rendering summarize.etable:

```py
    etable([fit1, fit2, fit3], coef_fmt="b (se) t (p)")
```
So I am simply taking it out for now and see if the docs build (they do locally) =)

**Comment by s3alfisc** [comment]
I have [taken out etable from the docs ](https://github.com/s3alfisc/pyfixest/commit/59e832bcb99212819375fe956d0b4e182bb1ef67) for now. This was indeed the root cause of the documentation build error - let's see if the website now successfully deploys!

**Comment by s3alfisc** [comment]
The website is not yet building completely as it should as I cannot point to a gh-pages branch. The branch should be created by the workflow, right?

**Comment by NKeleher** [comment]
@s3alfisc  Deployed! :tada: :tada:  :tada:  Hope this helps with the website and documentation going forward! 

Still odd behavior in the starting page...we'll get that figured out.

**Pull request merged**
